name: M7A 自动打包MFAAvalonia
on:
  push:
  workflow_dispatch:

jobs:
  build_package:
    runs-on: windows-latest
    steps:
      - name: 检出本仓库M7A代码
        uses: actions/checkout@v4

      - name: 下载MFAAvalonia最新win‑x64包
        id: download_step
        uses: robinraju/release-downloader@v1
        with:
          repository: MaaXYZ/MFAAvalonia
          latest: true
          filterAssets: "MFAAvalonia-.*-win-x64.zip"
          out-file-path: ./download

      - name: 解压 zip 压缩包
        run: Expand-Archive -Path ./download/*.zip -DestinationPath ./app -Force

      - name: 调试：查看解压后的目录结构
        run: Get-ChildItem ./app -Recurse

      - name: 定位程序根目录
        id: find_dir
        run: |
          $appDir = Get-ChildItem ./app -Directory | Select-Object -First 1 -ExpandProperty FullName
          echo "app_dir=$appDir" >> $env:GITHUB_OUTPUT

      - name: 复制M7A的assets脚本合并进程序目录
        run: |
          $target = "${{ steps.find_dir.outputs.app_dir }}/assets"
          # 确保目标文件夹存在
          if (-not (Test-Path $target)) {
              New-Item -ItemType Directory -Path $target -Force
          }
          Copy-Item -Path ./assets/* -Destination $target -Recurse -Force

      - name: 打包输出最终制品
        uses: actions/upload-artifact@v4
        with:
          name: M7A-release-win-x64
          path: ${{ steps.find_dir.outputs.app_dir }}/**
