# - 设置 VERSION 为具体版本号时（如 v1.2.3），下载指定版本
MAAFW_VERSION: ""
MFAA_VERSION: ""

on:
  push:
    tags:
      - "v*"
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "assets/**"
      - "interface.json"
      - "**.py"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "assets/**"
      - "interface.json"
      - "**.py"
  workflow_dispatch:

jobs:
  meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set_tag
        run: |
          if [ "${{ github.ref }}" = "refs/heads/${{ github.event.repository.default_branch }}" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/pull/${{ github.event.pull_request.number }}/merge" ]; then
            echo "tag=pull-request" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi
      - id: set_is_release
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v[0-9]+.[0-9]+.[0-9]+ ]]; then
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi
      - id: set_is_prerelease
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v[0-9]+.[0-9]+.[0-9]+-* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
      is_release: ${{ steps.set_is_release.outputs.is_release }}
      is_prerelease: ${{ steps.set_is_prerelease.outputs.is_prerelease }}

  install:
    needs: meta
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux-x86_64
          - os: ubuntu-latest
            name: linux-aarch64
          - os: ubuntu-latest
            name: android-x86_64
          - os: ubuntu-latest
            name: android-aarch64
          - os: macos-latest
            name: macos-x86_64
          - os: macos-latest
            name: macos-aarch64
          - os: windows-latest
            name: win-x86_64
          - os: windows-latest
            name: win-aarch64
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        if: ${{ !matrix.android }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/setup-node@v4
        if: ${{ !matrix.android }}
        with:
          node-version: '18'

      - name: Install MaaCLI
        if: ${{ !matrix.android }}
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "winget install MaaWpf.MaaCLI --accept-package-agreements --accept-source-agreements" >> $GITHUB_ENV
            winget install MaaWpf.MaaCLI --accept-package-agreements --accept-source-agreements
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            if [ -n "${{ env.MAAFW_VERSION }}" ]; then
              curl -sL https://github.com/MaaXYZ/MaaFramework/releases/download/${{ env.MAAFW_VERSION }}/MaaCLI-${{ env.MAAFW_VERSION }}-linux-x86_64.tar.gz | tar -xz
              mv MaaCLI-*/bin/maa /usr/local/bin/
            else
              pip install maa-cli
              maa self update
            fi
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            if [ -n "${{ env.MAAFW_VERSION }}" ]; then
              curl -sL https://github.com/MaaXYZ/MaaFramework/releases/download/${{ env.MAAFW_VERSION }}/MaaCLI-${{ env.MAAFW_VERSION }}-macos-x86_64.tar.gz | tar -xz
              mv MaaCLI-*/bin/maa /usr/local/bin/
            else
              brew install MaaWarp/tap/maa-cli
              maa self update
            fi
          fi
      - name: MaaCLI Deps
        if: ${{ !matrix.android }}
        shell: bash
        run: |
          maa install

      - name: Download MaaFramework Release
        uses: robinraju/release-downloader@v1.12
        with:
          repository: MaaXYZ/MaaFramework
          tag: ${{ env.MAAFW_VERSION }}
          fileName: "MaaFramework-${{ env.MAAFW_VERSION }}-${{ matrix.name }}*"
          out-file-path: framework
          unzip: true

      - name: Download MaaPipelineAssets Release
        uses: robinraju/release-downloader@v1.12
        with:
          repository: MaaXYZ/MaaPipelineAssets
          tag: ${{ env.MAAFW_VERSION }}
          fileName: "MaaPipelineAssets-${{ env.MAAFW_VERSION }}-${{ matrix.name }}*"
          out-file-path: pipeline
          unzip: true

      - name: Download MaaTemplateAssets Release
        uses: robinraju/release-downloader@v1.12
        with:
          repository: MaaXYZ/MaaTemplateAssets
          tag: ${{ env.MAAFW_VERSION }}
          fileName: "MaaTemplateAssets-${{ env.MAAFW_VERSION }}-${{ matrix.name }}*"
          out-file-path: template
          unzip: true

      - name: Generate debug project
        if: ${{ !matrix.android }}
        shell: bash
        run: |
          maa init

      - name: Update version
        run: |
          cd ./debug
          if [ "$RUNNER_OS" == "Windows" ]; then
            sed -i "s/version = .*/version = \"${{ needs.meta.outputs.tag }}\"/" interface.json
          else
            sed -i '' "s/version = .*/version = \"${{ needs.meta.outputs.tag }}\"/" interface.json
          fi

      - name: Merge MaaTemplateAssets and Project Resources
        if: ${{ !matrix.android }}
        shell: bash
        run: |
          cp ./assets/* ./debug/assets/resource/ -r
          if [ "$RUNNER_OS" == "Windows" ]; then
            cp interface.json ./debug/
          else
            cp ./interface.json ./debug/
          fi

      - name: Build MaaTemplateAssets
        if: ${{ !matrix.android }}
        shell: bash
        run: |
          cd debug
          maa build
          cd ..

      - name: Compress the Linux Distribution
        if: matrix.name == 'linux-x86_64' || matrix.name == 'linux-aarch64'
        shell: bash
        run: |
          cd ./debug
          mkdir release
          mv interface.json release/
          mv assets release/ -r
          mv deps release/
          mv install release/
          mv source release/

          cd release

          python3 -c "
          import json
          f = open('assets/pipeline/interface.json', 'r', encoding='utf-8')
          d = json.load(f)
          d['resource'][0]['path'] = ['./assets/resource', '../assets/resource']
          json.dump(d, open('assets/pipeline/interface.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=2, sort_keys=True, separators=(',', ':'))
          "

          cd ..
          zip -r ../maa-${{ needs.meta.outputs.tag }}-${{ matrix.name }}.zip ./debug/release

      - name: Compress the Android Distribution
        if: matrix.name == 'android-x86_64' || matrix.name == 'android-aarch64'
        shell: bash
        run: |
          cd ./debug
          mkdir release
          mv assets release/ -r
          mv deps release/
          mv install release/

          cd release

          python3 -c "
          import json
          f = open('assets/pipeline/interface.json', 'r', encoding='utf-8')
          d = json.load(f)
          d['resource'][0]['path'] = ['./assets/resource']
          json.dump(d, open('assets/pipeline/interface.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=2, sort_keys=True, separators=(',', ':'))
          "

          cd ..
          zip -r ../maa-${{ needs.meta.outputs.tag }}-${{ matrix.name }}.zip ./debug/release

      - name: Compress the Windows Distribution
        if: matrix.name == 'win-x86_64' || matrix.name == 'win-aarch64'
        shell: bash
        run: |
          cd ./debug
          mkdir release
          cp interface.json release/
          cp assets release/ -r
          cp deps release/
          cp install release/
          cp source release/

          cd release

          python3 -c "
          import json
          f = open('assets/pipeline/interface.json', 'r', encoding='utf-8')
          d = json.load(f)
          d['resource'][0]['path'] = ['./assets/resource', '../assets/resource']
          json.dump(d, open('assets/pipeline/interface.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=2, sort_keys=True, separators=(',', ':'))
          "

          cd ..
          zip -r ../maa-${{ needs.meta.outputs.tag }}-${{ matrix.name }}.zip ./debug/release

      - name: Compress the MacOS Distribution
        if: matrix.name == 'macos-x86_64' || matrix.name == 'macos-aarch64'
        shell: bash
        run: |
          cd ./debug
          mkdir release
          cp interface.json release/
          cp assets release/ -r
          cp deps release/
          cp install release/
          cp source release/

          cd release

          python3 -c "
          import json
          f = open('assets/pipeline/interface.json', 'r', encoding='utf-8')
          d = json.load(f)
          d['resource'][0]['path'] = ['./assets/resource', '../assets/resource']
          json.dump(d, open('assets/pipeline/interface.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=2, sort_keys=True, separators=(',', ':'))
          "

          cd ..
          zip -r ../maa-${{ needs.meta.outputs.tag }}-${{ matrix.name }}.zip ./debug/release

      - uses: actions/upload-artifact@v4
        with:
          name: maa-${{ needs.meta.outputs.tag }}-${{ matrix.name }}
          path: ./maa-${{ needs.meta.outputs.tag }}-${{ matrix.name }}.zip

  changelog:
    if: ${{ needs.meta.outputs.is_release == 'true' || needs.meta.outputs.is_prerelease == 'true' }}
    needs: meta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate Changelog
        uses: orhun/git-cliff-action@v4
        id: cliff
        with:
          config: cliff.toml
          args: >-
            -vv --latest --strip header
            ${{ needs.meta.outputs.is_prerelease == 'false' && '--tag-pattern "^v[0-9]+\\.[0-9]+\\.[0-9]+$"' || '' }}
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}

  release:
    if: ${{ needs.meta.outputs.is_release == 'true' || needs.meta.outputs.is_prerelease == 'true' }}
    needs: [meta, install, changelog]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: assets
      - run: |
          cd assets
          for f in *; do
            (cd $f && zip -r ../$f-${{ needs.meta.outputs.tag }}.zip .)
          done
      - uses: softprops/action-gh-release@v2
        with:
          files: assets/*
          tag_name: ${{ needs.meta.outputs.tag }}
          body: ${{ needs.changelog.outputs.release_body }}
          draft: false
          prerelease: ${{ needs.meta.outputs.is_prerelease == 'true' }}
